# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 07:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], default=None, max_length=20)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('total_fine', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(unique=True)),
                ('s_name', models.CharField(max_length=100)),
                ('s_year', models.CharField(max_length=10)),
                ('s_branch', models.CharField(choices=[('CS', 'COMPUTER SCIENCE'), ('EE', 'ELECTRICAL'), ('ECE', 'ELECTRONICS'), ('CE', 'CIVIL'), ('ME', 'MECHANICAL')], default=None, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='holiday',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
